### ISSUE TITLE
Minor typo in "3 - Natural Language Processing and LUIS" deck

### ISSUE THREAD

**Issue by ejadib** [GeekTrainer/help-desk-bot-lab#14]
In slide 14 of "3 - Natural Language Processing and LUIS" deck there is a typo. Instead of Turing it says Tur**n**ing

<img width="642" alt="capture" src="https://user-images.githubusercontent.com/307826/27081301-2060245c-5016-11e7-8a58-3abf1fcd492e.PNG">

**Comment by GeekTrainer** [comment]
Good catch. :-) Thank you.
