### ISSUE TITLE
URLs and keys are hard-coded in some labs.

### ISSUE THREAD

**Issue by GeekTrainer** [GeekTrainer/help-desk-bot-lab#2]
Can we update the Node lab to use either [dotenv](https://github.com/motdotla/dotenv) or something similar to provide environmental variables rather than hard-coding a default option? In particular this involves:

- Lab 2, with the LUIS model URL
- Lab 3, with the Azure Search information

**Comment by sdurandeu** [comment]
Sure. Our plan was to remove the keys before releasing the labs and replace them with placeholders. However, using dotenv might be a better option.

**Comment by rnrneverdies** [comment]
Fixed 
https://github.com/GeekTrainer/help-desk-bot-lab/commit/66693abb857144279d65e9debf8ea4c620966c98
https://github.com/GeekTrainer/help-desk-bot-lab/commit/7d30a006fba6fc89abf2fbe285ed79bdcb0de931
https://github.com/GeekTrainer/help-desk-bot-lab/commit/d222c11cab4e3fea7b6d9d770ce9eead969be286
https://github.com/GeekTrainer/help-desk-bot-lab/commit/4672a83afc940d0c28201277195c3f845466a2f9

**Comment by GeekTrainer** [comment]
👍
