### ISSUE TITLE
Adaptive Card on Lab 4

### ISSUE THREAD

**Issue by GeekTrainer** [GeekTrainer/help-desk-bot-lab#3]
Might it be worthwhile to create an adaptive card for Lab 4 rather than using the Hero Card? Give us another opportunity to show off the functionality.

**Comment by sdurandeu** [comment]
We gave this a second thought, and we believe that removing HeroCards from Lab 4 might not be ideal as it is a good feature to showcase. Also, using Adaptive Cards at that point might make the exercise more difficult to follow. The alternative we propose is adding it as a "Further Challenge Task" for Exercise 4, that includes not only the wording, but also some sample code (in the assets folder maybe). 

Thoughts?

**Comment by GeekTrainer** [comment]
Let's compromise and go with a thumbnail card. We are going to have a little graphic of a "bot" to display, and it'll work best if it's off to the side.

**Comment by sdurandeu** [comment]
Makes sense. This is how it would like like with the Thumbnail Card. It will be the same image for all documents, correct? Maybe we can use a different image background color for each article category (software, hardware, security, etc.).

![image](https://cloud.githubusercontent.com/assets/821193/26697144/5ecb41a0-46e7-11e7-8c64-fe58e8e7102e.png)

**Comment by GeekTrainer** [comment]
I like it!
